image: Visual Studio 2015
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
build:
  verbosity: minimal
install:
  - cmd: dir
  - cmd: cd "C:\Program Files (x86)\MSBuild"
  - cmd: dir
after_build:
  - cmd: 7z a "CITS_IE_Toolbar-%APPVEYOR_REPO_TAG_NAME%.zip" "%APPVEYOR_BUILD_FOLDER%\CITS IE Installer\bin\Release\CITS_IE_Toolbar.msi"
artifacts:
- path: '*.zip'
  name: cits
deploy:
- provider: GitHub
  description: New Build
  auth_token:
    secure: 12b24a050affabd508138989656eaf00e1c23b7f
  artifact: cits
  prerelease: false
  force_update: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true
