image: Visual Studio 2015
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
build:
  verbosity: minimal
install:
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%\CITS IE Installer\bin\Release"
  - cmd: dir
after_build:
  - cmd: 7z a "shantha.zip" "%APPVEYOR_BUILD_FOLDER%\CITS IE Installer\bin\Release\CITS_IE_Toolbar.msi"
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%\CITS IE Installer\bin\Release"
  - cmd: dir
artifacts:
- path: 'shantha.zip'
  name: cits
deploy:
- provider: GitHub
  description: New Build
  auth_token:
    secure: 12b24a050affabd508138989656eaf00e1c23b7f
  artifact: cits
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true
