version: 1.0.{build}
image: Visual Studio 2015
pull_requests:
  do_not_increment_build_number: true
configuration: Release
build:
  verbosity: minimal
install:
  - cmd: dir
  - cmd: cd "C:\Program Files (x86)\MSBuild"
  - cmd: dir
artifacts:
- path: '*.zip'
  name: cits
deploy:
- provider: GitHub
  description: New Build
  auth_token:
    secure: b0b0d69ae21ba3bce96932336dd7c3e9e89fd4b6
  artifact: cits
  prerelease: false
  force_update: false
  on:
    appveyor_repo_tag: true
